# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SMAC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SMAC
pod 'SwiftyJSON'
pod 'Alamofire', '~> 5.4.1'
pod 'SDWebImage'
pod 'SVProgressHUD'
pod 'MaterialComponents/Snackbar'
pod 'MBProgressHUD', '~> 1.0'
pod 'SwiftLint'
pod 'SideMenuSwift'
pod 'Eureka'
#pod 'SwiftySideMenuO'
pod 'CSSimpleSideMenu'
pod 'IQKeyboardManagerSwift', '6.5.0'

  target 'SMACTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SMACUITests' do
    # Pods for testing
  end

end
